baseURL = "/"
title = "Langium"
theme = "hugo-geekdoc"

# Required for publishing of previews as they are hosted in subdirs
relativeURLs = true

# Required to get well formatted code blocks
disablePathToLower = true
enableGitInfo = true
# Required if you want to render robots.txt template
enableRobotsTXT = true

[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.highlight]
    codeFences = false  # Disable Hugo's code highlighter as it conflicts with prism's highligher.
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[taxonomies]
  tag = "tags"


[build]
  noJSConfigInAssets = true
  minify = true
  [build.options]
    sourceMap = true

[security]
	[security.exec]
		allow = ['^go$', '^npx$', '^postcss$', '^babel$', '^git$']

[params]
  # (Optional, default 6) Set how many table of contents levels to be showed on page.
  # Use false to hide ToC, note that 0 will default to 6 (https://gohugo.io/functions/default/)
  # You can also specify this parameter per page in front matter.
  geekdocToC = 3

  # (Optional, default static/brand.svg) Set the path to a logo for the Geekdoc
  # relative to your 'static/' folder.
  geekdocLogo = "assets/langium_logo_w_nib.svg"

  # (Optional, default none) Add a link to your Legal Notice page to the site footer.
  # It can be either a remote url or a local file path relative to your content directory.
  #geekdocLegalNotice = "https://blog.example.com/legal"

  # (Optional, default none) Add a link to your Privacy Policy page to the site footer.
  # It can be either a remote url or a local file path relative to your content directory.
  # geekdocPrivacyPolicy = "https://www.typefox.io/imprint-privacy/#privacy"

  geekdocRepo = "https://github.com/eclipse-langium/langium-website"
  geekdocEditPath = "blob/main/hugo/content"

  # (Optional, default true) Add an anchor link to headlines.
  #geekdocAnchor = true

  # (Optional, default true) Copy anchor url to clipboard on click.
  #geekdocAnchorCopy = true

  # (Optional, default true) Enable or disable image lazy loading for images rendered
  # by the 'img' shortcode.
  #geekdocImageLazyLoading = true

  # (Optional, default false) Set HTMl <base> to .Site.BaseURL if enabled. It might be required
  # if a subdirectory is used within Hugos BaseURL.
  # See https://developer.mozilla.org/de/docs/Web/HTML/Element/base.
  geekdocOverwriteHTMLBase = true

  # (Optional, default false) Auto-decrease brightness of images and add a slightly grayscale to avoid
  # bright spots while using the dark mode.
  #geekdocDarkModeDim = false

  # (Optional, default true) Display a "Back to top" link in the site footer.
  #geekdocBackToTop = true

  # (Optional, default false) Enable or disable adding tags for post pages automatically to the navigation sidebar.
  #geekdocTagsToMenu = true

  # (Optional, default 'title') Configure how to sort file-tree menu entries. Possible options are 'title', 'linktitle',
  # 'date', 'publishdate', 'expirydate' or 'lastmod'. Every option can be used with a reverse modifier as well
  # e.g. 'title_reverse'.
  #geekdocFileTreeSortBy = "title"

  geekdocCollapseSection = true
  geekdocCollapseAllSections = true